name: pusher
description: Clone target and push.
inputs:
  owner:
    description: 'Repository Owner'
    required: true
  repository:
    description: 'Repository name'
    required: true
  branch:
    description: 'Branch name (default: main)'
    required: false
    default: "main"
  target:
    description: 'Target Repo'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Clone Github Repo
      uses: whyakari/github-repo-action@v3.1
      with:
        owner: ${{ inputs.owner }}
        repository: ${{ inputs.repository }}
        branch: ${{ inputs.branch }}
    - name: Config Git
      run: |
        git config --global user.name 'JonasGao'
        git config --global user.email 'jonasgao@users.noreply.github.com'
    - name: Config Git Repo
      env:
        RK: ${{ secrets.clash_rs_key }}
        RN: ${{ inputs.target }}
      run: |
        cd clash-rs
        git remote add backup "https://${RK}@github.com/JonasGao/${RN}.git"
    - name: Push
      run: |
        cd clash-rs
        git push backup HEAD:main --force
branding:
  icon: 'download'
  color: 'blue'
