name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: "0 0,6,12,16 * * *"
jobs:
  Explore:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'
      - name: Install pip dependencies
        run: pip install -r requirements.txt
      - name: Setup scripts
        run: |
          chmod u+x one.sh
          chmod u+x sync.sh
          chmod u+x reporter.sh
          chmod u+x down_latest.sh
      - name: Download latest report
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./down_latest.sh
      - name: Reporting...
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OUTLOOK_USER: ${{ secrets.OUTLOOK_USER }}
          OUTLOOK_KEY: ${{ secrets.OUTLOOK_KEY }}
          REPORT_RECEIVER: ${{ secrets.REPORT_RECEIVER }}
          RK: ${{ secrets.clash_rs_key }}
        run: ./one.sh
        shell: bash
      - name: Archive report.txt
        uses: actions/upload-artifact@v3
        with:
          name: report.txt
          path: report.txt
