name: Repo Jobs
run-name: Lets do some thing for our network~
on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: "0 0,6,12,16 * * *"
jobs:
  RepoReport:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install pip dependencies
        run: pip install -r requirements.txt
      - name: Download latest report
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: report/down_latest.sh
      - name: Reporting...
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OUTLOOK_USER: ${{ secrets.OUTLOOK_USER }}
          OUTLOOK_KEY: ${{ secrets.OUTLOOK_KEY }}
          REPORT_RECEIVER: ${{ secrets.REPORT_RECEIVER }}
        run: python report/reporter.py
        shell: bash
      - name: Archive latest_data.txt
        uses: actions/upload-artifact@v3
        with:
          name: latest_data
          path: data.txt
  RepoSync:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Sync...
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RK: ${{ secrets.clash_rs_key }}
        run: sync/sync.sh
        shell: bash