name: Send target repo reports
run-name: Send target repo reports
on: workflow_dispatch
jobs:
  RepoReport:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install pip dependencies
        run: pip install -r requirements.txt
      - name: Download latest report
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: report/down_latest.sh
      - name: Reporting...
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OUTLOOK_USER: ${{ secrets.OUTLOOK_USER }}
          OUTLOOK_KEY: ${{ secrets.OUTLOOK_KEY }}
          REPORT_RECEIVER: ${{ secrets.REPORT_RECEIVER }}
        run: python report/reporter.py
        shell: bash
      - name: Archive latest_data.txt
        uses: actions/upload-artifact@v4
        with:
          name: latest_data
          path: data.txt